make-java:
	javac *.java
	
run-java:
	java App
	
make-cpp:
	g++ *.cpp -o cpp.exe


make-java pour compiler le programme java
run-java pour lancer la conversion Java vers C++
make-cpp pour compiler le code C++ generé